name: test-jobs
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
permissions:
    contents: read
jobs:
    mutation:
        name: PHP ${{ matrix.php }}-${{ matrix.os }}

        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os:
                    - ubuntu-latest

                php:
                    - 8.1
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  tools: composer:v2, cs2pr
                  coverage: none

            -  name: Update composer
               run: composer self-update

            - name: Install dependencies with composer
              run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

            - name: run test
              id: run-test
              run: make test

            -   name: Archive tests output
                uses: actions/upload-artifact@v1
                with:
                    name: test-output
                    path: cache
                if: ${{ always() && steps.run-test.outcome == 'failure' }}